
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.4
    ports:
      - "8080:8080"       # Weaviate API + Console UI
      - "50051:50051"     # gRPC port (internal)
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_CONSOLE: "true"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data: